### use balance1
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber" : "1000000000",
  "amount" : 100
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber" : "1000000000",
  "amount" : 100
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "a31e97fd0a534e1b9ca23c9605c65de0",
  "accountNumber" : "1000000000",
  "amount" : 10000
}

### query transaction
GET http://localhost:8080/transaction/a672fc8ab1fc42f48c3bd7d9ef4d9c1c